language: r
cache: packages
matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.3
r_packages:
- covr
r_github_packages:
- ropensci/tabulizerjars
after_success:
- R -e 'library("covr");codecov()'
